# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Armando's Blog
# email: manguin98(at)gmail.com
description: >- # this means to ignore newlines until "baseurl:"
    My personal everything blog 🥯
baseurl: "" #
url: "" #
# twitter_username: dkfmakseh
github_username:  amascii


# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme

remote_theme: jekyll/minima
minima:
    skin: dark

# Collections
collections:
    books:
        sort-by: date
        output: true


# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
